services:
    mosquitto: 
      image:  eclipse-mosquitto
      container_name: mosquitto
      ports:
        - 1884:1883
      volumes:
        - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      networks:
        - rede

      restart: always
    

    rabbitMQ:
      image: rabbitmq:3.12-management 
      container_name: rabbitmq 
      ports:
        - "5673:5672"
        - "15673:15672"
      environment:
        RABBITMQ_DEFAULT_USER: metam
        RABBITMQ_DEFAULT_PASS: metam
        RABBITMQ_PLUGINS: rabbitmq_management
      networks:
        - "rede"
      depends_on:
        - mosquitto

      
    consumermqtt:
      build: ./deploy/mqttcon
      depends_on:
        - mosquitto
        - rabbitMQ    


      networks:
        - "rede"

      restart: always

networks:
  rede: